version: '2'

services:
  db:
    #image: mariadb:10.1
    image: mysql:8.0
    container_name: mysql
    ports:
      - 43306:3306
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_USER: filerun
      MYSQL_PASSWORD: filerun
      MYSQL_DATABASE: filerun
      TZ: Asia/Shanghai
    volumes:
      - ./data/db:/var/lib/mysql
  filerun:
    #image: filerun/filerun:8.1
    image: filerun:20220519
    container_name: filerun
    environment:
      FR_DB_HOST: db
      FR_DB_PORT: 3306
      FR_DB_NAME: filerun
      FR_DB_USER: filerun
      FR_DB_PASS: filerun
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
      TZ: Asia/Shanghai
    depends_on:
      - db
    links:
      - db:db
    ports:
      - "48080:80"
    volumes:
      - ./data/html:/var/www/html
      - ./data/user-files:/user-files